// Working on PPT
    // PPT - Kotlin Maps (T2W7)         <-- has more additional days... but will not bother with fine-grained details...
    // PPT - Kotlin Maps P2 (T2W8)      <-- has more additional days... but will not bother with fine-grained details...
    // PPT - Java Picture Processing (T2W9)